boltz/api.go
boltz/eventsource.go
boltz/eventsource_test.go
nursery/reverse.go
nursery/swap.go

Closes #12 
This PR fixes the cleanup of the SSE event streams after successful Swaps and refunds

fix: cleanup streams

---

boltzrpc/rpc.pb.go
boltzrpc/rpc.proto
cmd/boltzcli/boltzcli.go
cmd/boltzcli/client.go
cmd/boltzcli/commands.go
database/reverse.go
database/swap.go
rpcserver/router.go
rpcserver/serializer.go

feat: add ListSwaps command

---

Dockerfile

Boltz LND Dockerfile

---

docs/README.md
docs/configuration.md

Preview: https://boltz.gitbook.io/boltz-client-dev

docs: update node config

---

autoswap/autoswap.go
autoswap/autoswap_test.go
autoswap/budget.go
autoswap/config.go
autoswap/config_test.go
cmd/boltzcli/commands.go
cmd/boltzd/boltzd_test.go

- `AutoBudget` -> `Budget`
- `AutoBudgetInterval` ->  to `BudgetInterval`

refactor: rename autobudget config values

---

onchain/wallet/wallet.go
rpcserver/router.go

- fix: include wallet name in rpc error
- feat: check if subaccount exists on startup

feat: improve errors if wallet subaccount doesnt exist

---

boltz/api.go
boltz/musig.go
boltz/swaptree.go
boltz/transaction.go
nursery/nursery.go
nursery/reverse.go
nursery/swap.go
rpcserver/router.go

Various improvements to the `boltz` package to allow for better standalone usage.

refactor: improve boltz package

---

database/migration.go
database/migration_test.go

- fix: add back pairId column in migration
- feat: migration tests

fix: db migrations

---

boltz/api.go
cmd/boltzcli/commands.go

fix: autoswap setup swaptype

---

boltzrpc/client/connection.go
cmd/boltzcli/boltzcli.go
go.mod
go.sum
rpcserver/server.go

Makes it easier to use the rest api from other applications or browsers

feat: noTls option and cors for rpcserver

---

boltz/api.go
boltz/ws.go
config/config.go
nursery/nursery.go

feat: request proxy for http and ws api

---

cmd/boltzd/boltzd_test.go
nursery/refund.go

- fix: properly wait for sync in unlock test
- chore: add debug logs for flaky test

chore: fix flaky tests

---

cmd/boltzcli/commands.go
cmd/boltzcli/utils.go

feat: add more validators and `maxFeePercent` to autoswap setup

---

cmd/boltzcli/commands.go

feat: warning in autoswap setup if selected wallet has no balance

---

cmd/boltzd/boltzd.go
onchain/onchain.go
rpcserver/server.go

feat: handle shutdown signals gracefully

---

cmd/boltzd/boltzd.go
config/config.go
logger/logger.go
rpcserver/cert_test.go
rpcserver/rpcserver_test.go
test/test.go

Adds rotating logs using https://github.com/natefinch/lumberjack and two configuration values `logmaxsize` and `logmaxage`.

feat: rotating logs

---

nursery/swap.go

fix: correct service fee calculation for submarine swaps

---

.gitmodules
Makefile
nursery/chain.go
nursery/reverse.go
regtest.override.yml
rpcserver/router.go

- refactor: regtest as submodule
- test: override client in regtest

ci: include regtest as submodule

---

rpcserver/router.go
rpcserver/serializer.go

it can occur that the balance of a subaccount cant be fetched

fix: check for nil balance when serializing subaccount

---

onchain/wallet/wallet.go

was caused by auth handler not being freed

fix: gdk mem leak

---

onchain/wallet/wallet.go
onchain/wallet/wallet_test.go

green ui pastes both descriptors

feat: split core descriptors by new line

---

onchain/onchain.go

Previous: Implementation -> Notifier
Now: Implementation -> Internal state Update -> Notifier

fix: update internal blockHeight state before sending updates to subscribers

---

autoswap/autoswap.go
autoswap/chain_test.go
autoswap/config_test.go
autoswap/lightning.go
autoswap/lightning_test.go
autoswap/recommendation.go

check if wallet balance is sufficient when validating submarine swap recommendations.

feat: autoswap balance check

---

rpcserver/router.go
rpcserver/rpcserver_test.go

fix: check for same currency on existing credentials aswell

---

autoswap/RpcProvider_mock.go
autoswap/autoswap.go
autoswap/chain.go
autoswap/chain_test.go
autoswap/config_test.go
rpcserver/router.go

https://github.com/BoltzExchange/boltz-client/pull/339 with new base

feat: chain autoswap sweeps

---

autoswap/autoswap.go
autoswap/autoswap_test.go
autoswap/chain.go
autoswap/chain_test.go
autoswap/lightning.go
autoswap/lightning_test.go
rpcserver/autoswap.go

required in cases where recommendations were manually approved and one
has to make sure nothing changed in the meanwhile

refactor: check recommendations against previously accepted when executing

---

rpcserver/router.go

chain swaps amount checked the balance against the receiving amount
while the request specifies the sending amount

fix: check correct balance amount

---

internal/utils/version.go
internal/utils/version_test.go

fix: remove any version prefix before parsing

---

.github/workflows/release.yml

latest is now ubuntu 24 and might be the cause for runner issues

ci: run release on ubuntu 22

---

internal/rpcserver/rpcserver_test.go
internal/rpcserver/server.go

Only to be merged when boltz lockups aren't lowball anymore

feat: use multi tx provider for liquid

---

cmd/boltzcli/boltzcli.go
cmd/boltzcli/commands.go

closes: #433, chose a simpler command name.

feat: getpairs cli
