- boltz/api.go
- boltz/scripts.go
- boltz/scripts_test.go
- database/channel.go
- database/reverse.go
- database/swap.go
- nursery/channel.go
- nursery/swap.go
- rpcserver/router.go
- rpcserver/serializer.go
Because the `int` data type of Golang is either `int32` or `int64` depending on the architecture of the OS, the `/getpairs` request can fail on 32 bit operating systems because an overflow
This PR gets rid of the ambiguous `int` data type in the logic that interacts with the Boltz API to avoid that problem
Closes #40 
Thank you @brandonshope for finding this issue
> fix: replace int data type

- database/reverse.go
So today I couldn't finish a reverse swap with Boltz due to a weird error: `Could not decode claim address of Reverse Swap: decoded address is of unknown format`. Debugging with the almighty `log.Printf` revealed that the claim address is actually empty! But it was present in the database as I found using `sqlite3`. After about an hour of searching for clues I accidentally noticed that a particular field is used twice for different SQL columns. I have no idea how it worked before and why it stopped today (I used the same binary a couple of days ago), maybe the column order returned by SQLite was different so the `claimAddress` was put after `claimTransactionId` (which is of course empty before we sweep the funds!).
Anyway, now it's fixed. Hopefully, Boltz will see less failed swaps now, …
> Fix claimTransactionId typo

- Dockerfile
- Makefile
This will enable usage of the docker image on raspberry pi and Apple M1 platform
See: https://hub.docker.com/r/aphex3k/boltz-lnd/tags
> Build docker image for amd64, arm64, and arm

- boltz/btc.go
- boltz/liquid.go
- boltz/transaction.go
- cmd/boltzd/boltzd_test.go
- nursery/nursery.go
- nursery/reverse.go
- nursery/swap.go
Allow specifying a destination address for each output when creating a transaction. This simplifies any form of batching, currently swap refunds, but can be used for deferred claims of reverse / chain swaps aswell
> refactor: per-output addresses for transactions

- cmd/boltzcli/commands.go
`Green (https://blockstream.com/green).This` -> `Green (https://blockstream.com/green). This`
> fix: add space

- cmd/boltzcli/commands.go
> fix: make sure name is not empty when removing wallet in cli

- cln/cln.go
- config/config.go
- docs/README.md
This PR allows setting a custom cln server name through the `cln.servername` config value.
closes: #218
> feat: add config option for cln server name

- config/config.go
- electrum/electrum.go
- electrum/electrum_test.go
- onchain/onchain.go
- onchain/wallet/wallet.go
- rpcserver/server.go
- rpcserver/test/boltz.toml
- test/test.go
The GDK defaults (or the localhost urls for regtest) were always used before.
This is a breaking change to the config but I doubt that there are existing setups that use custom electrum servers.
> fix: pass configured electrum url to gdk

- rpcserver/rpcserver_test.go
it seems like the stream starts too late sometimes, causing the updates
to be missed
> test: make sure swap stream runs when mining block

- rpcserver/router.go
- rpcserver/rpcserver_test.go
The sqlite unique constraint ignores NULL values, so we do a check in go.
> fix: check for duplicate wallet names

- rpcserver/server.go
This allows clients to check the connection health at more regular intervals.
> feat: add keepalive policy to grpc server

- test/test.go
causes errors if old tx cache is still there
> chore: cleanup wallet test data

- onchain/wallet/wallet.go
gdk seems to have an issue with its size calculation for big transactions
> fix: slightly increase gdk fee estimation

- autoswap/lightning.go
we shouldnt try to swap out all inbound balance, so there is still
balance left for payments
> refactor: increase default ln autoswap reserve to 10 percent

- onchain/wallet/wallet.go
gdk sometimes returns 0.099 sat/vbyte
> fix: add gdk fee floor

- onchain/wallet/wallet.go
gdk started to impose their own limit which is off by 1
> fix: decrease `MaxInputs` by 1

- Makefile
- autoswap/lightning.go
- autoswap/rpc.go
- boltzrpc/serializers/utils.go
- lightning/lightning.go
- rpcserver/serializer.go
The cli accidently became dependant on the `lightning` package which links to the bolt12 rust lib.
This shouldn't be the case, so this PR moves some serializers to get rid of that dependancy aswell as adding the -static tag to the cli build command to make sure this doesn't happen again.
Not very happy with the current situation, as its easy to mess up.
> fix: dont include lightning lib in cli

- database/chain.go
- database/database.go
- database/reverse.go
- rpcserver/router.go
No need to check timeout when looking for claimable swaps - if they already timed out its even more urgent to claim.
> fix: remove timeout block height from claimable swaps query

- internal/database/chain.go
- internal/database/reverse.go
- internal/database/swap.go
- pkg/boltz/swaptree.go
- pkg/boltz/swaptree_test.go
`isLiquid` as a bool param in the interface is a bit weird
> refactor: swap tree init

- pkg/boltz/api.go
regression was introduce in: https://github.com/BoltzExchange/boltz-client/commit/c9930d072ed26fcc0462eaa449297ab634dc579b
> fix: legacy `getpairs` request

- pkg/boltz/ws.go
- pkg/boltz/ws_test.go
only create actual websocket connection when there are pending swaps and
close it if there are no more pending swaps
> feat: lazy websocket connection

- internal/onchain/onchain.go
1 sat/vbyte transactions can end up being stuck for days in the mempool.
> refactor: increase mainchain fee floor
